### ISSUE TITLE
Improve the order of jest configurations

### ISSUE THREAD

**Issue by jogelin** [angular-builders/jest#9]
I still have an issue with the multiple configurations extensions. It is working well but I still have a issue if I want to apply a global configurations to all of my `projects`. 

In my case, I would add a common `moduleNameMapper` but the only way for the moment is to add it in each `jest.config.js` of each project this config. 

After re-reading you code, I think we can avoid this and improve the priorities of extensions:

1) First use the default configs from the `default-config.ts` from you library
2) Then, apply configs from `package.json.jest` if specified
3) Then, apply configs from `workspaceRoot/jest.config.ts` if specified
4) Then, apply the default configs from the `default-project-config.ts` from you library (should be created)
5) Then, apply configs from `projectRoot/jest.config.ts` if specified
6) Then, apply config from `options` provided to the builder from `angular.json` (I would add the main options like `tsConfigFile`, `testPattern`, `moduleNameMapper`)

I am proposing this because it is exactly what I am doing by extending:
- `./jest.config.js` extends `node_modules/@angular-builders/jest/jest-config/default-config`  and I add the common `moduleNameMapper`
- `./projects/[projectName]/jest.config.js` extends `../../jest.config.js` (but I have to duplicate what the builder is doing....)

Would you accept a PR for that ?

**Comment by meltedspark** [comment]
Regarding your problem - why can't you just add a single _jest.config.js_ in the root and specify this config in each of the projects' options inside _angular.json_?  Or just add this config in _package.json_ (it will also affect all the projects)

Regarding your proposal...
Today it works this way:
1. Use the default configs from the _default-config.ts_ from the library
2. Add on top of it default project specific config (that is dynamic due to different root directories)
3. Add on top of it _package.json_ jest config if exists (for all projects)
or
Project specific config if it is specified inside _angular.json_
or
Or _jest.config.js_ from project directory (or src/ directory in case of non-project app) if exists.
_Notice that the default value of `configPath` in _schema.json_ is `jest.config.js` so if it exists it will be read_.

Given all this I'm not sure I understand what your proposal comes to add. Could you elaborate?  
Also, what would _default-project-config.ts_ contain?

P.S. It seems that I have to update the README as it is not clear from there that the configuration loading works in this way.

**Comment by jogelin** [comment]
Ok thanks, I specify only one config for each project then:

In `angular.json` for each project:
````json
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "configPath": "./jest.config.js"
          }
        },
```

Then in `jest.config.js`:
```
const defaultJestConfig = require('./node_modules/@angular-builders/jest/jest-config/default-config').default;

module.exports = {
  ...defaultJestConfig,
  globals: {
    ...defaultJestConfig.globals,
    'ts-jest': {
      tsConfigFile: `tsconfig.spec.json`
    }
  },
  moduleNameMapper: {
    ...defaultJestConfig.moduleNameMapper,
    '@my-lib-scope/(.*)': '<rootDir>/libs/$1/src'
  },

};
```

For me it's ok like this. I just propose a priorities to encourage people following conventions instead of configurations.

**Comment by meltedspark** [comment]
You don' have to merge it yourslef, the builder does that for you. Just put
the changes you'd like to make to the default config in your custom config.

**Comment by jogelin** [comment]
@meltedspark I am doing it because I want to run the tests in my IDE without specifying the path to `default-config` for each test...

**Comment by meltedspark** [comment]
Right. Anything I can do about that?

**Comment by jogelin** [comment]
No, I think this is only in my case.

But something else that I feel strange is the `configPath` to the common `jest.config.js`, I have to put 

```
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "configPath": "../../jest.config.js" <-- USUALLY CONFIGURATIONS IN angular.json DOESN'T USE THE PROJECT ROOT
          }
        },
```

It is not a big deal for me but it should be specify...or at least, when a config is not loaded, log a warning because I lost some times ;)
